# Generated by Django 5.1.1 on 2024-09-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(max_length=400)),
                ("price", models.FloatField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Science", "Science"),
                            ("Mathematics", "Mathematics"),
                            ("Literature", "Literature"),
                            ("Others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="notes/")),
            ],
        ),
    ]
