# Generated by Django 5.1.1 on 2024-09-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notes",
            name="Title",
        ),
        migrations.AddField(
            model_name="notes",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="notes",
            name="title",
            field=models.CharField(default="Untitled", max_length=100, unique=True),
        ),
    ]
