# Generated by Django 5.1.1 on 2024-10-17 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def set_default_user(apps, schema_editor):
    Notes = apps.get_model('api', 'Notes')
    User = apps.get_model('auth', 'User')
    default_user = User.objects.first()  # Get the first user or create a new one if needed
    if default_user:  # Check if there is a user to assign
        Notes.objects.filter(user=None).update(user=default_user)

class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_notes_title_notes_image_notes_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                null=True,  # Set null=True to allow existing rows to remain without a user
            ),
        ),
        migrations.RunPython(set_default_user),  # Run the function to set the default user
    ]
