# Generated by Django 5.1.1 on 2024-10-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_notes_user_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="username",
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
