# Generated by Django 5.1.1 on 2024-12-01 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_cartitem_username_alter_cartitem_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="note",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.notes"
            ),
        ),
    ]
